### PR TITLE
Issues/315 csv parsing

### PR DESCRIPTION
**Pull request by zdennis**
This PR gets the CSV source reports working again for Counter, Pmc, Mendeley, ALM stats (with and without private sources), and ALM combined stats (with and without private sources). It applies to issue #315.

#### How to run the changes

First fetch/pull and check out this branch.

Next, you can run the below rake command for the individual reports affected:

```
bin/rake  report:all_stats
```

This rake will generate all of the reports corresponding report files in `data/report_YYYY-MM-DD.zip` where YYYY-MM-DD is today's date respectively.  Unzip this file, and then you'll see all of the individual reports.  

Based on your current development data you should be able spot check a few items in each file.

#### Overview of the changes

Primary goal: to able to generate the Mendeley, Counter, Pmc, and ALM-related CSV reports once again. 

* Separate the concept of a `Source` from the concept of a report. 
* Separate the concept of a report from the concept of its format, e.g. CSV.
* Separate the concept of the generic Source report from the by-month Source report which require different inputs and provide different outputs. 
* When necessary provide a way to extend the implementation with minimal modifications necessary to existing code (e.g. [CounterReport](https://github.com/articlemetrics/lagotto/blob/issues/315_csv_parsing/app/models/reports/counter_report.rb#L6-L16) archives this thru overriding operational methods on the base class and [CounterByMonthReport](https://github.com/articlemetrics/lagotto/blob/issues/315_csv_parsing/app/models/reports/counter_by_month_report.rb#L3) achieves this thru a `register_value_provider_for_format` hook.
* introducing the user of an iterator method `#each_line_item` on each report which is relied on for generating CSV. This is intended to allow for optimizations on how data is loaded to be introduced while minimize the amount of code that would be impacted by such a change.

#### Things Not Handled By This PR

* This doesn't change how reports are stored to disk or zipped up.

#### Previous questions from originally opening the PR.

_These may no longer be valid based on the most recent changes._

 Right now this breaks the XML stats/reports. See below questions...

#### Questions

@mfenner, a few questions for you... 

* It looks like the combined stats for Counter and Pmc was generated using `xml_views` previously. This appears to be stored in the `extra` field. I don't have this for any of my data locally. Can you confirm that this indeed still exists and needs to the xml reports need to be kept?

* `Source#to_csv` has been removed because it doesn't appear we're using it for any source reports outside of Counter, Pmc, and Mendeley. 

* Any objections to removing the `#to_csv` on Counter/Pmc/Mendeley and to push up the the new corresponding calls to the rake file? E.g.

```
  desc 'Generate CSV file with Mendeley stats'
  task :mendeley_stats => :environment do
    filename = "mendeley_stats.csv"

    # check that source is installed
    source = Source.visible.where(name: "mendeley").first
    next if source.nil?

    csv = MendeleyReport.new(source).to_csv
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by mfenner** [comment]
The xml count is `total - (pdf + html)`, so you could generate an xml report without using the `extra` field (which is basically providing backwards compatibility in older API versions). If that logic would be to complex, we can leave it out.

**Comment by mfenner** [comment]
Removing `Source#to_csv` is fine.

**Comment by mfenner** [comment]
I usually like to keep as much as possible in a model and use the rake file only as a wrapper, mainly because I find testing much easier this way. In your experience, is that not necessarily true?

**Comment by zdennis** [comment]
> The xml count is total - (pdf + html), so you could generate an xml report without using the extra field (which is basically providing backwards compatibility in older API versions). If that logic would be to complex, we can leave it out.

I don't think it will be to complex. I'll push up a change shortly including this. It only applies to Counter source report though, yes?

> I usually like to keep as much as possible in a model and use the rake file only as a wrapper, mainly because I find testing much easier this way. In your experience, is that not necessarily true?

I think we're on the same page. I'll push shortly the change for your review.

**Comment by zdennis** [comment]
@mfenner, on [this line from counter.rb](https://github.com/articlemetrics/lagotto/blob/762f9ea2c6394a48478242e5793abb9dd7e19c56/app/models/sources/counter.rb#L58) a caller could get the XML count if they passed in `format: 'xml'`. 

However, if they ran the generic `'counter'` report they wouldn't get XML count, just HTML, PDF, and total as seen on [this line from counter.rb](https://github.com/articlemetrics/lagotto/blob/762f9ea2c6394a48478242e5793abb9dd7e19c56/app/models/sources/counter.rb#L78)

Was that intentional or should the XML count show up in the generic counter report as well?

**Comment by mfenner** [comment]
Counter XML is an edge case, therefore the implementation it is a bit hidden. Let's include XML in the generic counter report as well and treat it similar to pdf and html in the reports.

**Comment by zdennis** [comment]
@mfenner, this PR is ready for review. Let me know if you have any questions about any thing. Thanks!

**Comment by mfenner** [comment]
Thanks. Will get to it later today.

**Comment by mfenner** [comment]
@zdennis I get a undefined method `gitxshared_examples_for` error. Should that be `shared_examples_for`?

**Comment by zdennis** [comment]
@mfenner, good catch. That definitely shouldn't be there and should be exactly what you thought. PR #353 removes that bad reference.

**Pull request merged**
