### PR TITLE
Issues/339 export csv report

### PR DESCRIPTION
**Pull request by zdennis**
This PR is for issue #339 . It's nearing completion and should be completed sometime tomorrow. It is far enough along however for review and feedback. 

### Summary of this PR

This PR makes it possible to export the ALM Cumulative report (`alm_report.csv`) to Zenodo. In doing so, it provides a generic way to export data out of Lagotto. 

At a high level the following things happen:

* Reports are written to disk via `ReportWriter` using the rake report tasks. When they are written they are logged to `ReportWriteLog`.
* Zip archives are created using `ReportZipper`.
* `report:export_to_zenodo` is a new task  that will take the most recently exported ALM combined stats report, and it upload it to Zenodo in the background using Sidekiq and a `DataExportJob`

At a slightly lower level... 

* Behind the `rake report:all_stats` and related rake tasks is the`ReportWriter`. This is a high level class that knows how to create specific reports using lower level classes. As it writes these reports to disk it logs this to `ReportWriteLog`. 
  * The `ReportWriteLog` is used to keep track of what reports were written and when. It also keeps track of the file path for the report on the local file-system. 
  * `ReportWriter` and `ReportWriteLog` are intended to minimize the number of places where code has to worry about report filenames, filename conventions, where files live, etc.
* The `rake report:zip` task is still intact as well with the following changes:
  *  It uses a new object, `ReportZipper`,  to handle knowing how to zip up certain reports and what files to include in them.
* The`rake report:export_to_zenodo` task handles generating the Zenodo export, queuing up a `ZenodoDataExport` job, and then a background worker will pick it up and do the work.
* Exceptions during the export are logged as `Alert`(s).

#### Get a Zenodo Sandbox account set up

* Get a Zenodo Sandbox account here: https://sandbox.zenodo.org
* Get a personal token / API key by going to https://sandbox.zenodo.org/account/settings/applications/ once you've logged in and generate a new Personal access token
* Update your `.env` file to have both `ZENODO_API_KEY=...` and  `ZENODO_URL=https://sandbox.zenodo.org` environment variables.

_Note: when ready to go to production the same steps will have to be repeated on Zenodo's main site: https://zenodo.org

#### Update your env variables

New ENV variables have been added that you'll need to configure in you `.env` file. You can find them in the `.env.example` file. You'll need:

```
CREATOR=Public Library of Science
ZENODO_KEY=YOUR_KEY_HERE
ZENODO_URL=https://sandbox.zenodo.org/api/
SITENAMELONG="PLOS ALM"
```

#### Checkout and run migrations

This adds couple new tables to the DB to keep track of reports written to disk.

```
bin/rake db:migrate
```

#### Run reports, zipping them up, exporting to Zenodo

Next, run the following rake tasks:

```
bin/rake report:all_stats report:zip report:export_to_zenodo
```

_Note: Make sure you have Sidekiq up and running otherwise the Zenodo export won't happen._

#### Check "My Uploads" in Zenodo's Web Interface

Go to https://sandbox.zenodo.org/deposit/ 

On the right hand side you should see an upload listed. If you don't see an upload listed, then there are two things to check:

##### First thing to check

Look for an `Alert` record to have been created outlining any exceptions from talking with Zenodo

##### Second thing to check

Look at the last  `ZenodoDataExport` record to see if it has a `starting_export_at` and `finishing_export_at` fields set. If both of these are `nil` then they either haven't started or they started and failed (see Alerts); if `starting_export_at` is populated, but not `finishing_export_at` then the export is in progress. If `finished_exporting_at` has  value then the file is on Zenodo, try to refresh your browser.

##### READMEs in the Zip

The `alm_report.zip` includes a `README.md` file. It gets pulled in from `docs/readmes/alm_combined_stats_report.md`. Its contents need to be fleshed out.

##### Date  in the zip filename

I have not included the `alm_report.zip` filename. This was only out of lack of time. It isn't huge effort to get in there, but I wanted to move on to the next issue and start making headway.  I figure we can always circle back and in this in later if need be.

##### Removing files after export

Right now the files exported (alm_report.zip) is not removed after export. The Zenodo export only knows about the zip file so it could remove that when done. However, there are other files left on the system. 

Let's chat and see if we should have a cron job remove any/all files older than X days or if we want to this be integrated into the system in another way. The benefit of keeping the file around for a short period of time is that it may not be available on Zenodo right away and if there are any particular issues there will be a grace period for someone to investigate on the server w/o having to re-run a long a potentially long running report.

##### Zenodo Gem

The Zenodo gem's [Pull request 7](https://github.com/sprotocols/zenodo/pull/7) is the last one we're waiting on. Once that is merged in and released we can use the official [Zenodo ruby gem](http://rubygems.org/gems/zenodo/).

I think these changes will be merged in this weekend at the latest, but if they're not, we'll want to have ALM fork my repository until they are. Right now, the `Gemfile` uses my fork of the Zenodo ruby gem.

### CODE REVIEW

**Comment by zdennis** [comment]
@mfenner, I've updated the PR description and pushed all of my changes. There are two things to note at the bottom of the PR description that we'll probably want to chat about tomorrow.

Let me know if yo run into any issues running or reviewing the code. Thanks,

**Comment by zdennis** [comment]
Rebased in the latest changes on master and force pushed this branch.

**Comment by mfenner** [comment]
@zdennis, I have worked through the pull request. Per your comments:

* I have updated the README, in sync with the text we use for the Zenodo description
* Data in the zip filename. We can leave it out for now.
* removing files after export: I decided to remove the `data` folder, and store the reports in `tmp/reports`, all other files we generated temporarily in `tmp/files`. See #378.

**Comment by zdennis** [comment]
@mfenner, thanks for reviewing, make those updates, and merging in!

**Pull request merged**
